apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
    app.kubernetes.io/instance: cicd-demo-argocd
  name: seldon-deployment-example
spec:
  annotations:
    deployment_version: v0
    project_name: Simple Model Prediction
  name: seldon-deployment
  oauth_key: oauth-key
  oauth_secret: oauth-secret
  predictors:
  - annotations:
      predictor_version: v1
    componentSpecs:
    - spec:
        containers:
        - image: "127.0.0.1:5000/gsunner/simple-model:M01"
          imagePullPolicy: IfNotPresent
          name: simple-model
          resources:
            requests:
              memory: 1Mi
        terminationGracePeriodSeconds: 20
    graph:
      children: []
      endpoint:
        service_host: localhost
        service_port: 9000
        type: REST
      implementation: UNKNOWN_IMPLEMENTATION
      name: simple-model
      type: MODEL
    labels:
      version: simple-model-predictor
    name: simple-model-predictor
    replicas: 1